---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cashew-os
# description will be included in the image's metadata
description: Durable Laptop Appliance. A specialized, immutable Fedora image for high-performance minimalism. Keyboard based.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: files
    files:
      - source: dotfiles/config.jsonc
        destination: /etc/xdg/waybar/config.jsonc # Copy the  Waybar config

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/brew:latest /system_files /
      # - RUN --mount=type=cache,dst=/var/cache \
      #   --mount=type=cache,dst=/var/log \
      #   --mount=type=tmpfs,dst=/tmp \
      #   /usr/bin/systemctl preset brew-setup.service && \
      #   /usr/bin/systemctl preset brew-update.timer && \
      #   /usr/bin/systemctl preset brew-upgrade.timer

  # ##############################
  #             DNF
  # ##############################

  - type: dnf
    repos:
      copr:
        - ublue-os/packages
        - ryanabx/cosmic-epoch

    install:
      packages:
        - git
        - micro
        - powertop
        - podman-docker
        - fastfetch
        - xfce4-taskmanager
        - baobab
        # - loupe
        - flameshot
        - qview
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  # ##############################
  #        FLATPACKS
  # ##############################
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.github.tchx84.Flatseal
          - net.waterfox.waterfox #web browser
          - org.kde.kate #code editor
          - com.sidevesh.Luminance # brightness control
          - io.github.kolunmi.Bazaar
          - io.podman_desktop.PodmanDesktop
          - io.github.DenysMb.Kontainer
          - com.github.rafostar.Clapper
          - org.gnome.Decibels
          - org.gnome.Papers
          - org.gnome.Logs
          - org.xfce.mousepad
          # - org.kde.okular #document reader
          # - org.kde.filelight #disk space analyzer
          # - org.gnome.Loupe #image viewer
          - org.gnome.Calculator # calculator
      # - org.gnome.baobab
      # - org.xfce.ristretto
      # - org.flameshot.Flameshot

      - scope: user # Also add Flathub user repo, but no user packages

  # ##############################
  #        SCRIPTS
  # ##############################
  - type: script
    scripts:
      - optimizer.sh
      - hardener.sh
      - autotiling.sh
  #

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
