---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cashew-os
# description will be included in the image's metadata
description: Durable Laptop Appliance. A specialized, immutable Fedora image for high-performance minimalism. Keyboard based.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      # --- Existing files ---
      - source: system
        destination: /

      # --- Dotfiles
      - source: dotfiles/wallpaper.jxl
        destination: /usr/share/backgrounds/default.jxl  
      - source: dotfiles/lockscreen.jxl
        destination: /usr/share/backgrounds/lockscreen.jxl
      - source: dotfiles/dunst/dunstrc
        destination: /etc/xdg/dunst/dunstrc

      - source: dotfiles/sway/sway.conf
        destination: /etc/sway/config.d/sway.conf
      - source: dotfiles/waybar/config.jsonc
        destination: /etc/xdg/waybar/config.jsonc
      - source: dotfiles/foot/foot.ini
        destination: /etc/xdg/foot/foot.ini
      - source: dotfiles/swaylock/swaylock.conf
        destination: /etc/swaylock/config

      - source: dotfiles/lxqt.conf
        destination: /etc/xdg/lxqt/lxqt.conf
      - source: dotfiles/pcmanfm-qt/settings.conf
        destination: /etc/xdg/pcmanfm-qt/default/settings.conf
      - source: dotfiles/lxqt-qtxdg.conf
        destination: /etc/xdg/qtxdg.conf
      - source: dotfiles/portals.conf
        destination: /etc/xdg/xdg-desktop-portal/sway-portals.conf
      - source: dotfiles/qt6/qt6.conf
        destination: /etc/environment.d/qt6.conf
      - source: dotfiles/qt6/qt6ct.conf
        destination: /etc/xdg/qt6ct/qt6ct.conf

# homebrew installation
  # - type: containerfile
  #   snippets:
  #     - COPY --from=ghcr.io/ublue-os/brew:latest /system_files /

  # ##############################
  #             DNF
  # ##############################

  - type: dnf
    repos:
      copr:
        - ublue-os/packages

    install:
      packages:
        - powertop
        - git
        - micro
        - fastfetch
        - power-profiles-daemon
        - xdg-desktop-portal-lxqt
        - qt6ct

        # --- The Native Stack ---
        - qview # Ultra-fast Qt6 image viewer
        - mpv # Best-in-class
        - pcmanfm-qt # Native Qt6 file manager
        - lxqt-archiver # Native archive tool (right-click integration)
        - screengrab # Native Wayland capture
        - qps # Pro task manager (replacing xfce4-taskmanager)
        - copyq
        - qmmp
        # - nlock

    remove:
      packages:
        # - firefox
        # - firefox-langpacks
        - xfce4-panel
        - Thunar
        - tuned
        - tuned-ppd
        # - xdg-desktop-portal-gtk
        - blueman


  # ##############################
  #        FLATPACKS
  # ##############################
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - io.github.ebonjaeger.bluejay #bluetooth manager
          # - net.waterfox.waterfox #web browser
          - org.kde.okular
          - org.kde.kate #code editor
          - org.kde.kcalc
          - io.github.kolunmi.Bazaar
          - io.github.DenysMb.Kontainer
          - com.github.tchx84.Flatseal

          # - io.podman_desktop.PodmanDesktop
          # - org.gnome.Logs
          # - org.gnome.Papers
          # - com.sidevesh.Luminance # brightness control

      - scope: user # Also add Flathub user repo, but no user packages

  # ##############################
  #        SCRIPTS
  # ##############################
  - type: script
    scripts:
      - optimizer.sh
      - hardener.sh
      - autotiling.sh
      - cleanup.sh
  #

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
