[Appearance]
# Style: Fusion is the low-RAM C++ native choice
style=fusion
# Palette: High-contrast Dark
color_scheme_path=/usr/share/qt6ct/colors/darker.conf
custom_palette=true
# Icons: Paper
icon_theme=Paper
standard_dialogs=default

[Interface]
# Clean minimalist appliance defaults
activate_item_on_single_click=1
menus_have_icons=false