image=/usr/share/backgrounds/default.jxl
scaling=fill
ignore-empty-password
show-failed-attempts
show-caps-lock



indicator-radius=100
indicator-thickness=10
line-uses-inside


# --- General Appearance ---
color=1a1b26
indicator-radius=100
indicator-thickness=10
line-uses-inside

# --- Colors: Inside (The circle center) ---
inside-color=1a1b26
inside-clear-color=1a1b26
inside-ver-color=7aa2f7
inside-wrong-color=f7768e

# --- Colors: Ring (The outer border) ---
ring-color=7aa2f7
ring-clear-color=7dcfff
ring-ver-color=c0caf5
ring-wrong-color=1a1b26

# --- Colors: Text ---
text-color=c0caf5
text-clear-color=c0caf5
text-ver-color=1a1b26
text-wrong-color=1a1b26

# --- Colors: Highlights (The 'typing' segments) ---
key-hl-color=c0caf5
bs-hl-color=f7768e
separator-color=1a1b26