# Change kill command to Mod+Q (removes Shift requirement)
bindsym $mod+q kill

# --- Startup ---
exec copyq
# exec qps -mini


# --- Visuals ---
gaps inner 10
gaps outer 5
smart_gaps on
smart_borders on

# --- Borders & Colors ---
default_border pixel 2
default_floating_border pixel 2

# Border Colors (Matches your terminal-themed CV style)
# class                 border  backgr. text    indicator child_border
# client.focused          #00ff00 #000000 #00ff00 #2e9ef4   #00ff00
# client.focused_inactive #444444 #000000 #ffffff #484e50   #444444
# client.unfocused        #222222 #000000 #888888 #292d2e   #222222
